services:
  workbench_2:
    build:
      context: .
      dockerfile: workbench-2-dockerfile
    ports:
      - "8000:8000"  # Map the webserver port from the container to the host
    restart: always
    volumes:
      - "/sys/devices/platform/soc/3f200000.gpio:/sys/devices/platform/soc/3f200000.gpio" #Pass through GPIO
      - "/sys/class/gpio:/sys/class/gpio"