services:
  workbench_2:
    build:
      context: .
      dockerfile: workbench-2-dockerfile
    ports:
      - "8000:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - .:/app