services:
  robot_1:
    build: .
    environment:
      - ROBOT_NAME=robot1  # Device path for the robot
    ports:
      - "8001:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB_robot1:/dev/ttyUSB_robot1"  # Pass through the USB device
  robot_2:
    build: .
    environment:
      - ROBOT_PORT=robot2  # Device path for the robot
    ports:
      - "8002:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB_robot2:/dev/ttyUSB_robot2"  # Pass through the USB device
  robot_3:
    build: .
    environment:
      - ROBOT_PORT=robot3  # Device path for the robot
    ports:
      - "8003:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB_robot3:/dev/ttyUSB_robot3"  # Pass through the USB device